helm:
  parameters:
  - name: image.name
    value: ghcr.io/laurimaila/personal-website
    forcestring: true
  - name: image.tag
    value: 1.3.3
    forcestring: true
  - name: ingress.host
    value: vm2.laurimaila.com
    forcestring: false
  - name: ingress.cors.allowOrigin
    value: https://vm2.laurimaila.com
    forcestring: false
  - name: ingress.annotations.traefik\.ingress\.kubernetes\.io/router\.tls\.certresolver
    value: myresolver
    forcestring: false
