image:
  repository: ghcr.io/laurimaila/personal-website
  tag: "1.1.0"
  pullPolicy: IfNotPresent

imagePullSecrets:
  name: regcred

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  className: nginx
  host: vm2.laurimaila.com
  tls:
    secretName: frontend-tls

resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "500m"
