image:
  repository: ghcr.io/laurimaila/liquibase-svc
  tag: "1.4.2"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: regcred

postgres:
  host: postgres-service
  existingSecret: "postgres-secret"
  secretKeys:
    userKey: POSTGRES_USER
    passwordKey: POSTGRES_PASSWORD
    dbKey: POSTGRES_DB

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "250m"
