helm:
  parameters:
  - name: ingress.host
    value: -dev.laurimaila.com
    forcestring: false
  - name: ingress.cors.allowOrigin
    value: https://vm2-dev.laurimaila.com
    forcestring: false
  - name: ingress.annotations.traefik\.ingress\.kubernetes\.io/router\.tls\.certresolver
    value: myresolver
    forcestring: false
  - name: image.tag
    value: dev@sha256:aad2c3bf77409a4fb49595c962adc3fac993edd900769ad55041d6d6a332dc90
    forcestring: true
  - name: image.name
    value: ghcr.io/laurimaila/physics-svc
    forcestring: true
