image:
  repository: ghcr.io/laurimaila/backend-personal-website
  tag: "1.4.2"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: regcred

postgres:
  host: postgres-service
  existingSecret: "postgres-secret"
  secretKeys:
    userKey: POSTGRES_USER
    passwordKey: POSTGRES_PASSWORD
    dbKey: POSTGRES_DB

jwt:
  existingSecret: "backend-secrets"
  secretKey: JWT_SECRET_KEY

ingress:
  enabled: true
  className: traefik
  host: api2.laurimaila.com
  tls:
    secretName: backend-tls
  cors:
    allowOrigin: "https://vm2.laurimaila.com"

physicsService:
  host: "physics-svc"
  port: "50051"

resources:
  requests:
    memory: "256Mi"
    cpu: "200m"
  limits:
    memory: "512Mi"
    cpu: "500m"
