image:
  repository: ghcr.io/laurimaila/personal-website-backend
  tag: "latest"
  pullPolicy: IfNotPresent

imagePullSecrets:
  name: regcred

postgres:
  host: postgres-service
  existingSecret: "postgres-secret"
  secretKeys:
    userKey: POSTGRES_USER
    passwordKey: POSTGRES_PASSWORD
    dbKey: POSTGRES_DB

jwt:
  existingSecret: "backend-secrets"
  secretKey: JWT_SECRET_KEY

ingress:
  enabled: true
  className: nginx
  host: api2.laurimaila.com
  tls:
    secretName: backend-tls
  cors:
    allowOrigin: "https://vm2.laurimaila.com"

resources:
  requests:
    memory: "256Mi"
    cpu: "200m"
  limits:
    memory: "512Mi"
    cpu: "500m"
